@GameRankingApi_HostAddress = http://localhost:5194

### 1. 获取排行榜
GET {{GameRankingApi_HostAddress}}/api/score
Accept: application/json

###

### 2. 添加成绩
POST {{GameRankingApi_HostAddress}}/api/score
Content-Type: application/json

{
    "playerName": "小也",
    "score": 2500,
    "gameName": "测试游戏"
}

###

### 3. 再次获取排行榜
GET {{GameRankingApi_HostAddress}}/api/score
Accept: application/json

### 根据 ID 获取成绩
GET {{GameRankingApi_HostAddress}}/api/score/1
Accept: application/json

### 正常修改成绩
PUT {{GameRankingApi_HostAddress}}/api/score/1
Content-Type: application/json

{
    "playerName": "小也",
    "score": 5000,
    "gameName": "测试游戏"
}

GET {{GameRankingApi_HostAddress}}/api/score/1
Accept: application/json