@GameRankingApi_HostAddress = http://localhost:5194

### 获取全部排行榜
GET {{GameRankingApi_HostAddress}}/api/score
Accept: application/json

###

### 根据 ID 获取成绩
GET {{GameRankingApi_HostAddress}}/api/score/1
Accept: application/json

###

### 添加玩家成绩
POST {{GameRankingApi_HostAddress}}/api/score
Content-Type: application/json

{
    "playerName": "小也",
    "score": 2500,
    "gameName": "测试游戏"
}