@GameRankingApi_HostAddress = http://localhost:5194

### 获取全部排行榜
GET {{GameRankingApi_HostAddress}}/api/score
Accept: application/json

###

### 根据 ID 获取成绩
GET {{GameRankingApi_HostAddress}}/api/score/1
Accept: application/json

###

### 添加玩家成绩
POST {{GameRankingApi_HostAddress}}/api/score
Content-Type: application/json

{
    "playerName": "小也",
    "score": 2500,
    "gameName": "测试游戏"
}


###

### 修改玩家成绩
PUT {{GameRankingApi_HostAddress}}/api/score/2
Content-Type: application/json

{
    "playerName": "小也",
    "score": 5000,
    "gameName": "新游戏"
}

###

### 修改不存在的成绩
PUT {{GameRankingApi_HostAddress}}/api/score/999
Content-Type: application/json

{
    "playerName": "不存在的人",
    "score": 9999,
    "gameName": "不存在的游戏"
}